name: Auto Sync media-autobuild_suite Fork

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Sync upstream
        run: |
          git remote remove upstream || true
          git remote add upstream https://github.com/m-ab-s/media-autobuild_suite.git
          git fetch upstream
          git checkout master
          git merge upstream/master --no-edit || exit 0
          git push origin master
